version: '2'
services:
  blueocean:
    image: own/blueocean
    container_name: blueocean
    restart: always
    volumes:
    - /srv/docker/blueocean:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
